apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svc-db
  name: svc-db
  namespace: microshop
spec:
  clusterIP: None
  ports:
    - name: 3306-3306
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: db
status:
  loadBalancer: {}
