apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: svc-backend
  name: svc-backend
  namespace: microshop
spec:
  ports:
    - name: 3000-3000
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: api
  type: ClusterIP
status:
  loadBalancer: {}
