apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: log-agent
  name: log-agent
  namespace: microshop
spec:
  selector:
    matchLabels:
      app: log-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: log-agent
    spec:
      containers:
        - image: busybox
          name: busybox
          resources: {}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
          command:
            [
              "/bin/sh",
              "-c",
              "while true; do echo $(date) >> /var/log/agent.log; sleep 5; done",
            ]
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
status: {}
